WIP - Add Redis
DecipherNow/helm-charts pull request #735
Opened 2020-09-02 20:27 UTC by bcmendoza

**Please provide enough information so that others can review your pull request:**

1. Explain the **details** for making this change. What existing problem does the pull request solve? If it resolves an existing issue, be sure to use a Github [keyword](https://help.github.com/en/articles/closing-issues-using-keywords) to automatically close it.

<br/><br/>
- Configures Control API and Catalog to use Redis rather than filepersister/Data
- Adds an option for the user to configure an external Redis service (e.g. AWS Elasticache)
- Adds a stateful set of a Redis server for persisting configs from Control API and Catalog
- Removes Catalog's use of Data as its config source
- Removes internal JWT, Redis, Data, and Mongo

2. What **changes to custom.yaml** are required?

<br/><br/>

3. Have you documented any additional setup steps or configurations options?

<br/><br/>
Not yet, WIP

4. Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

<br/><br/>

2020-09-02 20:57 UTC, chrisbsmith reviewed
I am only reviewing this on my phone, but we need to add some documentation to the PR. Specifically, if we are going to advertise that users can leverage AWS Elasticache, we need to document very specifically the minimum IAM role that is needed for this to work. We may even want to write a terraform script to do this for the users.

2020-09-03 14:11 UTC, bcmendoza commented
> I am only reviewing this on my phone, but we need to add some documentation to the PR. Specifically, if we are going to advertise that users can leverage AWS Elasticache, we need to document very specifically the minimum IAM role that is needed for this to work. We may even want to write a terraform script to do this for the users.

Sounds good. It's still a WIP, but I will make sure to document the steps for setting up an example connection to AWS Elasticache.

2020-09-21 19:18 UTC, tilleryd commented
@bcmendoza Is this still a WIP? We would like to deploy without gm-data in the 1.3 test environment.

2020-09-21 21:41 UTC, zoemccormick requested changes
a couple of questions but everything is functioning as described! awesome to get ride of the catalog-> int data -> int jwt complexities and mesh configs

2020-09-21 21:41 UTC, zoemccormick commented on fabric/control-api/json/services/listener.json
> +      "spiffe://{{ .Values.global.spire.trust_domain}}/data"
will data need to be able to route to all services?

2020-09-21 21:41 UTC, zoemccormick commented on fabric/control-api/values.yaml
> -      value: '{{ .Values.controlApi.pvc_mount_point }}'
can we remove the pvc by default or use a flag to include/not include it since this will now use redis? https://github.com/DecipherNow/helm-charts/blob/b67a59bbe9365774c76b99e9960ad289bf39e4cc/fabric/control-api/templates/control-api.yaml#L150-L156

2020-09-21 21:41 UTC, zoemccormick commented on global.yaml
> +
can some of these be moved out of global values and set as defaults in the redis values? to avoid complicating the globals again

2020-09-23 15:53 UTC, zoemccormick commented on fabric/control-api/json/services/listener.json
> +      "spiffe://{{ .Values.global.spire.trust_domain}}/edge"
this will actually still need a check for jwt so data can connect to jwt

```suggestion
      "spiffe://{{ .Values.global.spire.trust_domain}}/edge"{{- if and (eq .service.serviceName "jwt-security") (.Values.global.data.external.enabled) }},
      "spiffe://{{ .Values.global.spire.trust_domain}}/data"
```

2020-09-23 15:55 UTC, zoemccormick commented on fabric/control-api/json/services/listener.json
> +      "spiffe://{{ .Values.global.spire.trust_domain}}/edge"
Im not sure how to handle the case that "external" data is not installed? without the data.external.enabled global option

2020-09-23 17:02 UTC, bcmendoza commented on fabric/control-api/json/services/listener.json
> +      "spiffe://{{ .Values.global.spire.trust_domain}}/edge"
`data` is installed by default now... should I have kept the option to disable it?

2020-09-23 17:13 UTC, zoemccormick commented on fabric/control-api/json/services/listener.json
> +      "spiffe://{{ .Values.global.spire.trust_domain}}/edge"
im not sure - the ability to disable it was an [issue](https://github.com/DecipherNow/helm-charts/issues/646),  [PR](https://github.com/DecipherNow/helm-charts/pull/664). @chrisbsmith @moosecanswim thoughts on whether or not Data should always be installed by default?

2020-09-23 17:27 UTC, chrisbsmith commented on fabric/control-api/json/services/listener.json
> +      "spiffe://{{ .Values.global.spire.trust_domain}}/edge"
No, data should not be installed by default.  Now that we're using Redis, no gm-datas should be installed with a default config.

2020-09-23 18:35 UTC, bcmendoza commented on fabric/control-api/json/services/listener.json
> +      "spiffe://{{ .Values.global.spire.trust_domain}}/edge"
Ah okay thanks. I will restore the option to toggle it and add a check for it in this template

2020-09-24 15:57 UTC, zoemccormick approved these changes
lgtm!

2020-09-24 16:45 UTC, merged

2020-09-24 16:58 UTC, chrisbsmith commented
@bcmendoza when the documentation for using AWS Elasticache Redis is available, can you please link it here?